### ISSUE TITLE
请问这个可以在op上用么

### ISSUE THREAD

**Issue by qingninglx** [HsOjo/PyEsDialerGD#1]
开发的老哥没用做路由器的版本，用起来有点麻烦。。如果可以的话可以详细教一下吗  感激不尽

**Comment by callmeraysoap** [comment]
Traceback (most recent call last):
  File "C:\Users\qqq\Desktop\PyEsDialerGD-master\__main__.py", line 5, in <module>
    client = EsDialerGD()
  File "C:\Users\qqq\Desktop\PyEsDialerGD-master\es_dialer_gd.py", line 37, in __init__
    raise Exception('Can not load config.')
Exception: Can not load config.
那个数据库是读取不到吗，有详细一点教程吗？小白用户
