### ISSUE TITLE
请问一下这个错误是什么呢，已经在data上修改sample和重命名了

### ISSUE THREAD

**Issue by callmeraysoap** [HsOjo/PyEsDialerGD#2]
Traceback (most recent call last):
  File "C:\Users\r***\Desktop\PyEsDialerGD-master\__main__.py", line 5, in <module>
    client = EsDialerGD()
  File "C:\Users\r***\Desktop\PyEsDialerGD-master\es_dialer_gd.py", line 37, in __init__
    raise Exception('Can not load config.')
Exception: Can not load config.

**Comment by cch9897** [comment]
注意json文件里的格式
